# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build with Conda

on:
    push:
        branches:
            - master
    pull_request:
    workflow_dispatch:

jobs:
    build:
        name: Python ${{ matrix.version }} on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest]
                version: [3.7, 3.8, 3.9]

        steps:
            -   name: Cancel Previous Runs
                uses: styfle/cancel-workflow-action@0.9.1
                with:
                    access_token: ${{ github.token }}

            -   uses: actions/checkout@v2

            -   name: Set up Python
                uses: actions/setup-python@v2
                with:
                    python-version: ${{ matrix.version }}

            -   name: Install dependencies
                run: pip install -e .[test]

            -   name: Info Python
                run: |
                    which python
                    python --version

            -   name: Info installed packages
                run: pip list

            -   name: Run codecov
                uses: codecov/codecov-action@v2
                with:
                    file: ./coverage.xml
                    name: codecov-umbrella

    Linting:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Set up Python 3.9 on ubuntu-latest
                uses: actions/setup-python@v2
                with:
                    python-version: 3.9

            -   name: Install linters
                run: pip install "flake8>=3.8.0" "pydocstyle>=5.0.0"

            -   name: Python info
                run: |
                    which python
                    python --version

            -   name: Installed packages
                run: pip list

            -   name: Run flake8
                run: flake8 nanoCAT tests
                continue-on-error: true
