# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build with Conda

on:
    push:
        branches:
            - master
    pull_request:

env:
    AMS_URL: https://downloads.scm.com/Downloads/download2021/bin/ams2021.105.pc64_linux.intelmpi.bin.tgz
    AMS: ams2021.105
    SCMLICENSE: license.txt
    AMSHOME: ams
    AMSBIN: ams/bin
    AMSRESOURCES: ams/atomicdata

jobs:
    ams:
        name: Load AMS
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Enable cache
                id: enable-cache
                uses: actions/cache@v2
                with:
                    path: ams
                    key: ${{ env.AMS }}

            -   name: Download AMS
                if: steps.enable-cache.outputs.cache-hit != 'true'
                env:
                    WGETRC: "${{ secrets.WGETRC }}"
                run: |
                    echo "$WGETRC" > ~/.wgetrc
                    wget -q "$AMS_URL" -O ams.bin.tgz

            -   name: Unpack archive
                if: steps.enable-cache.outputs.cache-hit != 'true'
                run: |
                    tar -xvzf ams.bin.tgz
                    mv $AMS_DIR ams
                    chmod -R U+rx ams

    tests:
        name: Tests ${{ matrix.version }} on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        needs: [ams]
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest]
                version: [3.7, 3.8, 3.9]

        steps:
            -   name: Cancel Previous Runs
                uses: styfle/cancel-workflow-action@0.9.1
                with:
                    access_token: ${{ github.token }}

            -   uses: actions/checkout@v2

            -   name: Load AMS
                id: load-ams
                uses: actions/cache@v2
                if: matrix.os == 'ubuntu-latest'
                with:
                    path: ams
                    key: ${{ env.AMS }}

            -   name: Set up Conda
                uses: s-weigand/setup-conda@v1
                with:
                    update-conda: false

            -   name: Install dependencies
                run: |
                    conda create -n test -c conda-forge python=${{ matrix.version }} "rdkit>=2021.03.4"
                    source $CONDA/bin/activate test
                    pip install -e .[test]

            -   name: Info Conda
                run: |
                    source $CONDA/bin/activate test
                    conda info

            -   name: Info installed packages
                run: conda list -n test

            -   name: Run tests
                env:
                    SCMLICENSE: "${{ secrets.SCMLICENSE }}"
                run: |
                    source $CONDA/bin/activate test
                    case "${{ steps.load-ams.outputs.cache-hit }}" in
                        "true")
                            echo "$SCMLICENSE" > license.txt
                            pytest
                            ;;
                        *)
                            pytest -m "not slow" ;;
                    esac

            -   name: Run codecov
                uses: codecov/codecov-action@v2
                with:
                    file: ./coverage.xml
                    name: codecov-umbrella

    Linting:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Set up Python 3.9 on ubuntu-latest
                uses: actions/setup-python@v2
                with:
                    python-version: 3.9

            -   name: Install linters
                run: pip install "flake8>=3.8.0" "pydocstyle>=5.0.0"

            -   name: Python info
                run: |
                    which python
                    python --version

            -   name: Installed packages
                run: pip list

            -   name: Run flake8
                run: flake8 nanoCAT tests
                continue-on-error: true
